feat(01-building-blocks): converts to success

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,10 +12,10 @@ jobs:
           
           runs-on: ubuntu-latest
           steps:
-             - name : Failed step
-               run : | 
-                     echo "I will fail"
-                     exit 1
+            #  - name : Failed step
+            #    run : | 
+            #          echo "I will fail"
+            #          exit 1
              - name : Say good bye
                run : | 
                      echo "Good Bye!"
